### ISSUE TITLE
REMOVE AUTO CROPPING / DISABLE DOCUMENT BORDER DETECTION

### ISSUE THREAD

**Issue by jujupec** [WebsiteBeaver/react-native-document-scanner-plugin#110] opened 2024-01-04 10:36 UTC
When we take a photo with the module, it detects the document and automatically crops the photo. Would it be possible to disable this but still keep the ability to crop the photo afterwards?

**Comment by dmarcs** [comment] 2024-03-21 15:56
duplicate of https://github.com/WebsiteBeaver/react-native-document-scanner-plugin/issues/45

**Closed by dmarcs** 2024-03-21 15:56 UTC

**Comment by skyllex94** [comment] 2024-09-14 17:11
Any update on this, if we can have it as an option in the properties of DocumentScanner.scanDocument() that would be amazing!
