### ISSUE TITLE
Android : Image dimensions causing window to overflow from screen

### ISSUE THREAD

**Issue by jmazier-j2d** [WebsiteBeaver/react-native-document-scanner-plugin#4] opened 2022-09-05 12:54 UTC
I've integrated your plugin within my app, so far, I'm having only minor issues (maxScan is not working properly on android).

But, one of my developers found a major issue with the "crop" screen. On certain device, image from the system camera are returned with a tall height, this needs to be resized or somehow contains within the view, otherwise, we can't use the button below to validate the crop / capture. This only appears on a OnePlus 5. I've been testing in simulator with all native android phones and many samsung devices, without experiencing this issue. It must be something particular from OnePlus' phones. If you need further information, please let me know.

![image](https://user-images.githubusercontent.com/48437234/188453561-7a8bd3c9-dbee-46ba-ad2b-c5bdd3238fbd.png)

**Comment by dmarcs** [comment] 2022-09-06 21:24
Unfortunately I don't have a OnePlus, so I can't easily figure out the issue.

maxNumDocuments should be working though. Maybe they're using maxScan instead of maxNumDocuments.

**Comment by dmarcs** [comment] 2022-09-07 21:17
Which version of Android are you using? I probably need to subtract the navbar height.

**Comment by jmazier-j2d** [comment] 2022-10-19 09:55
@dmarcs Experiencing the same issue on some Samsung S20 running android 12.

I couldn't reproduce it on my side, I do not have a physical device with this issue. One of my colleague does, so I can still run test with him if needed @dmarcs .
Also, would you accept PR for this issue ? We are using your package in a production app and we can't afford to have so many devices blocked by this issue. We would love to help and contribute to this awesome package.

**Comment by dmarcs** [comment] 2022-10-24 00:02
@jmazier-j2d Yes I'll gladly accept PRs. Unfortunately I can't reproduce this since I don't have a OnePlus,

**Comment by jmazier-j2d** [comment] 2022-10-24 12:37
> @jmazier-j2d Yes I'll gladly accept PRs. Unfortunately I can't reproduce this since I don't have a OnePlus,

Great ! Our dev opened a PR on the dependency causing this very issue (but you already replied to it) : https://github.com/WebsiteBeaver/android-document-scanner/pull/8

Glad we can help somehow contributing to this great project ! Seems like the problem can also be reproduced on some Galaxy S device (I'm waiting for the user to confirm the exact device).

**Comment by dmarcs** [comment] 2022-11-02 13:30
fixed in 1.0.4 https://github.com/WebsiteBeaver/android-document-scanner/pull/8

set a minimum required height on the bottom control bar, so that a very tall image doesn't hide the bottom control bar

**Closed by dmarcs** 2022-11-02 13:30 UTC
